In [2]:
import torch

In [8]:
x = torch.rand(1)
print(x.item(), x.dtype)

0.45998096466064453 torch.float32


In [12]:
x = torch.ones(2, 2, dtype=torch.float16)
print(x, x.size())

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16) torch.Size([2, 2])


In [15]:
torch.cuda.is_available()

False

In [22]:
x = torch.ones(2, 2)
y = torch.rand(2, 2)
print(x)
print()
print(y)
print()
x.add_(y)
y = torch.mul(x, x)
print(y)

tensor([[1., 1.],
        [1., 1.]])

tensor([[0.5873, 0.3598],
        [0.8591, 0.2256]])

tensor([[2.5196, 1.8491],
        [3.4564, 1.5020]])


In [27]:
x = torch.rand(20)
print(x.size())
x = x.view(-1, 5)
print()
print(x)
print(x.size())

torch.Size([20])

tensor([[0.0709, 0.5539, 0.2188, 0.3548, 0.9830],
        [0.1393, 0.7873, 0.0581, 0.7974, 0.8430],
        [0.1059, 0.7763, 0.4861, 0.0822, 0.8532],
        [0.2878, 0.1188, 0.0562, 0.5184, 0.3845]])
torch.Size([4, 5])


In [35]:
print(x[:, 0])
print(x[2, :])

tensor([0.0709, 0.1393, 0.1059, 0.2878])
tensor([0.1059, 0.7763, 0.4861, 0.0822, 0.8532])


In [42]:
rows = list(x.size())[0]
columns = list(x.size())[1]
print(rows, columns)
print(x[rows - 1][columns - 1].item())

4 5
0.3844839930534363


In [46]:
x = torch.rand(2)
print(x, type(x))
x = x.numpy()
print(x, type(x))

tensor([0.4779, 0.3553]) <class 'torch.Tensor'>
[0.4778831 0.3553477] <class 'numpy.ndarray'>


In [50]:
import numpy as np

x = np.ones([2, 2])
print(x, type(x))
y = torch.from_numpy(x)
print(y, type(y))

[[1. 1.]
 [1. 1.]] <class 'numpy.ndarray'>
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64) <class 'torch.Tensor'>


In [59]:
x = torch.rand(3, requires_grad=True)
y = torch.rand(3)
z = torch.mul(x, y)
z.add_(1)
print(z)

tensor([1.1422, 1.0678, 1.2852], grad_fn=<AddBackward0>)


In [68]:
x, y = torch.tensor(1), torch.tensor(2)
w = torch.ones(1, requires_grad = True)
print(x, y, w)
print('=' * 50)
for epoch in range(5):
  y_hat = x * w
  loss = (y_hat - y) ** 2
  loss.backward()
  print(w, w.grad)
  with torch.no_grad():
    w.add_(w.grad)
  w.grad.zero_()

tensor(1) tensor(2) tensor([1.], requires_grad=True)
tensor([1.], requires_grad=True) tensor([-2.])
tensor([-1.], requires_grad=True) tensor([-6.])
tensor([-7.], requires_grad=True) tensor([-18.])
tensor([-25.], requires_grad=True) tensor([-54.])
tensor([-79.], requires_grad=True) tensor([-162.])
