In [ ]:
import numpy as np

In [ ]:
a = [1, 2, 3.2, 'hello', [[['a', 3]]]]
a

[1, 2, 3.2, 'hello', [[['a', 3]]]]

In [ ]:
a = np.array([1, 1, 1], dtype='int32')
a

array([1, 1, 1], dtype=int32)

In [ ]:
b = np.array([
              [1, 1, 1, 1],
              [2, 2, 2, 2]
])

In [ ]:
a.dtype

dtype('int32')

In [ ]:
c = np.array([
              [1, 2, 3, 4, 10],
              [5, 6, 7, 8, 11]
])
c

array([[ 1,  2,  3,  4, 10],
       [ 5,  6,  7,  8, 11]])

In [ ]:
c[1, 2]

7

In [ ]:
c[0, :]

array([ 1,  2,  3,  4, 10])

In [ ]:
c[:, 0]

array([1, 5])

In [ ]:
c[:, :]

array([[ 1,  2,  3,  4, 10],
       [ 5,  6,  7,  8, 11]])

In [ ]:
c[1, 0::2]

array([ 5,  7, 11])

In [ ]:
c[0, 0] = 20
c

array([[20,  2,  3,  4, 10],
       [ 5,  6,  7,  8, 11]])

In [ ]:
c[0] = [1, 2, 3, 4, 5]

In [ ]:
ones_array = np.ones([2, 2], dtype='int32')
zeros_array = np.zeros([2, 2], dtype='int32')
print(zeros_array)
print()
print(ones_array)

[[0 0]
 [0 0]]

[[1 1]
 [1 1]]


In [ ]:
full_array = np.full([2, 2], 23)
full_array

array([[23, 23],
       [23, 23]])

In [ ]:
full_array = np.full_like(c, 23)
full_array

array([[23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23]])

In [ ]:
rnd_array = np.random.rand(c.shape[0], c.shape[1])
rnd_array

array([[0.22288119, 0.31363616, 0.75219641, 0.11537217, 0.46113258],
       [0.68752023, 0.35635707, 0.75695123, 0.86672163, 0.51611031]])

In [ ]:
rnd_array = np.random.randint(10, 15, size=c.shape)
rnd_array

array([[13, 12, 13, 11, 10],
       [12, 10, 14, 14, 13]])

In [ ]:
d = c.copy()
d[0, 0] = 200
d

array([[200,  20,  20,  20,  20],
       [  5,   6,   7,   8,  11]])

In [ ]:
c

array([[20, 20, 20, 20, 20],
       [ 5,  6,  7,  8, 11]])

In [ ]:
tmp = (ones_array + 3) ** 2
tmp = np.sin(tmp)
tmp

array([[-0.28790332, -0.28790332],
       [-0.28790332, -0.28790332]])

In [ ]:
a = np.ones([2, 4])
b = np.full([4, 3], 4)
print(a)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]


In [ ]:
np.matmul(a, b)

array([[16., 16., 16.],
       [16., 16., 16.]])

In [ ]:
idy = np.identity(5)

In [ ]:
np.linalg.det(idy)

1.0

In [ ]:
c

array([[20, 20, 20, 20, 20],
       [ 5,  6,  7,  8, 11]])

In [ ]:
np.min(c, axis=1)

array([20,  5])

In [ ]:
c.reshape([5, 2])

array([[20, 20],
       [20, 20],
       [20,  5],
       [ 6,  7],
       [ 8, 11]])